/**
 * ============================================================================
 * 📊 CHART WIDGET - Renders Plotly Charts from Backend
 * ============================================================================
 *
 * Displays interactive charts generated by the backend's Chart Generator.
 * Supports all 80+ chart types with Macrocomm branding.
 */

'use client';

import React, { useEffect, useRef } from 'react';
import { Maximize2, Download, ZoomIn, ZoomOut } from 'lucide-react';

interface ChartWidgetProps {
  chartData: any; // Plotly chart JSON from backend
  title?: string;
  description?: string;
  height?: number;
}

export const ChartWidget: React.FC<ChartWidgetProps> = ({
  chartData,
  title,
  description,
  height = 400,
}) => {
  const chartRef = useRef<HTMLDivElement>(null);
  const [isFullscreen, setIsFullscreen] = React.useState(false);

  useEffect(() => {
    if (!chartRef.current || !chartData) return;

    // Dynamically load Plotly
    const loadPlotly = async () => {
      try {
        const Plotly = await import('plotly.js-dist-min');

        // Configure chart with Macrocomm theme
        const config = {
          displayModeBar: true,
          displaylogo: false,
          responsive: true,
          modeBarButtonsToRemove: ['pan2d', 'lasso2d', 'select2d'],
          toImageButtonOptions: {
            format: 'png',
            filename: title || 'chart',
            height: 1080,
            width: 1920,
            scale: 2,
          },
        };

        // Apply Macrocomm branding to layout
        const layout = {
          ...chartData.layout,
          paper_bgcolor: 'rgba(26, 31, 46, 0.5)', // --color-surface
          plot_bgcolor: 'rgba(26, 31, 46, 0.3)',
          font: {
            family: 'Inter, Segoe UI, sans-serif',
            color: '#F8FAFC', // --color-foreground
            size: 12,
          },
          margin: { t: 40, r: 40, b: 40, l: 60 },
          hovermode: 'closest',
          hoverlabel: {
            bgcolor: '#1A1F2E',
            bordercolor: '#FF6E00',
            font: {
              family: 'Inter, Segoe UI, sans-serif',
              color: '#F8FAFC',
            },
          },
        };

        // Render chart (only if ref is available)
        if (chartRef.current) {
          Plotly.newPlot(chartRef.current, chartData.data, layout, config);
        }
      } catch (error) {
        console.error('Failed to load Plotly:', error);
      }
    };

    loadPlotly();

    return () => {
      if (chartRef.current) {
        const Plotly = (window as any).Plotly;
        if (Plotly) {
          Plotly.purge(chartRef.current);
        }
      }
    };
  }, [chartData, title]);

  const handleFullscreen = () => {
    if (!chartRef.current) return;
    if (chartRef.current.requestFullscreen) {
      chartRef.current.requestFullscreen();
      setIsFullscreen(true);
    }
  };

  return (
    <div className="glass border border-white/10 rounded-xl overflow-hidden">
      {/* Header */}
      {(title || description) && (
        <div className="p-4 border-b border-border">
          <div className="flex items-start justify-between">
            <div className="flex-1">
              {title && (
                <h3 className="font-semibold text-foreground mb-1">{title}</h3>
              )}
              {description && (
                <p className="text-sm text-foreground-muted">{description}</p>
              )}
            </div>
            <button
              onClick={handleFullscreen}
              className="p-2 hover:bg-surface-hover rounded-lg transition-colors"
              title="Fullscreen"
            >
              <Maximize2 className="w-4 h-4 text-foreground-muted" />
            </button>
          </div>
        </div>
      )}

      {/* Chart Container */}
      <div
        ref={chartRef}
        style={{ height: `${height}px` }}
        className="w-full"
      />
    </div>
  );
};
